# Generated by Django 6.0.2 on 2026-02-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address_anonymized', models.GenericIPAddressField(blank=True, null=True)),
                ('referer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Seitenaufruf',
                'verbose_name_plural': 'Seitenaufrufe',
                'ordering': ['-timestamp'],
            },
        ),
    ]
